-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  email text,
  full_name text,
  avatar_url text,
  updated_at timestamp with time zone,
  
  constraint username_length check (char_length(full_name) >= 3)
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
  for update using (auth.uid() = id);

-- Create a table for products
create table products (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  price decimal(10,2) not null,
  image_url text,
  category text,
  stock_quantity integer default 0,
  stripe_price_id text, -- Optional Stripe Price ID connection
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for products
alter table products enable row level security;

create policy "Products are viewable by everyone." on products
  for select using (true);

-- Create orders table
create table orders (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users not null,
  items jsonb not null,
  total_amount decimal(10,2) not null,
  status text not null default 'pending',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up RLS for orders
alter table orders enable row level security;

create policy "Users can view their own orders." on orders
  for select using (auth.uid() = user_id);

create policy "Users can insert their own orders." on orders
  for insert with check (auth.uid() = user_id);

-- Function to handle new user signup
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, full_name, avatar_url)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- [NEW] Allow guest orders by making user_id nullable
-- ALTER TABLE orders ALTER COLUMN user_id DROP NOT NULL;

-- [NEW] RPC Function to securely decrement stock
-- This bypasses RLS issues for stock updates and ensures atomicity
create or replace function decrement_stock(product_id bigint, quantity_to_decrement int)
returns void
language plpgsql
security definer
as $$
begin
  update products
  set stock_quantity = greatest(0, stock_quantity - quantity_to_decrement)
  where id = product_id;
end;
$$;

-- [STORAGE] Create 'products' bucket if not exists
insert into storage.buckets (id, name, public)
values ('products', 'products', true)
on conflict (id) do nothing;

-- [STORAGE] Policy: Everyone can View (Select)
create policy "Public Access"
on storage.objects for select
using ( bucket_id = 'products' );

-- [STORAGE] Policy: Everyone can Upload (Insert)
create policy "Public Upload"
on storage.objects for insert
with check ( bucket_id = 'products' );

-- [SECURITY] Admin flag and RLS updates
alter table profiles add column if not exists is_admin boolean default false;

-- Secure Products Table (Admin Only)
drop policy if exists "Products are viewable by everyone." on products;
create policy "Products are viewable by everyone." on products for select using (true);
create policy "Admins can insert products" on products for insert with check (
  exists (select 1 from profiles where id = auth.uid() and is_admin = true)
);
create policy "Admins can update products" on products for update using (
  exists (select 1 from profiles where id = auth.uid() and is_admin = true)
);
create policy "Admins can delete products" on products for delete using (
  exists (select 1 from profiles where id = auth.uid() and is_admin = true)
);

-- Secure Storage (Admin Only Upload)
drop policy if exists "Public Upload" on storage.objects;
create policy "Admins can upload product images" on storage.objects for insert with check (
  bucket_id = 'products' and
  exists (select 1 from profiles where id = auth.uid() and is_admin = true)
);

